#!/bin/sh

set -e

SCRIPT_DIR="$(CDPATH="" cd -- "$(dirname -- "$0")" && pwd)"

CDPATH="" cd -- "$SCRIPT_DIR/.."

[ -n "$GITHUB_TOKEN" ] || {
  echo GITHUB_TOKEN must be set
  exit 1
}

script/bindown install -q goreleaser
script/bindown install -q semver-next

GITHUB_SHA="${GITHUB_SHA:-"$(git rev-parse HEAD)"}"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-"WillAbides/handcrafted"}"

bin/semver-next "$GITHUB_REPOSITORY" -r "$GITHUB_SHA" --create-tag --require-labels
